FROM node:20-alpine as build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci --production=false
COPY frontend/ .

ARG VITE_API_URL
ARG VITE_WS_URL
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Note: NGINX logic will be securely overwritten from docker-compose volumes binding
EXPOSE 80
